name: 2 - Formulas Scheduler (Secrets)

on:
  schedule:
  - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Ritchie Installation & Initialization
        run: |
            curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash
            echo '{"addCommons":false, "sendMetrics":false, "runType":"local"}' | rit init --stdin

      - name: Ritchie Formula Get Github User (Python) Execution
        env:
            USERNAME_DEMO: ${{ secrets.USERNAME_DEMO }}
            USERNAME_CREDENTIAL: ${{ secrets.USERNAME_CREDENTIAL }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            rit add repo --provider="Github" --name="formulas-github" --repoUrl="https://github.com/GuillaumeFalourd/formulas-github" --priority=1
            rit set credential --provider=github --fields=username,token --values="$USERNAME_CREDENTIAL","$GITHUB_TOKEN"
            rit github get user --rit_github_username="$USERNAME_DEMO" --rit_repo_details="no" --rit_keep_file="no"
