name: Formulas Scheduler (Action)

on:
 schedule:
    - cron: '0 0 * * *'
 workflow_dispatch:

jobs:
  shell-action_job:
    runs-on: ubuntu-latest
    name: Ritchie Action Shell
    steps:
    - name: Run SHELL Ritchie Action Command
      uses: GuillaumeFalourd/ritchie-action-shell@v2.2
      with:
        rit-repo-url: https://github.com/ZupIT/ritchie-formulas-demo
        rit-formula-command: rit demo coffee-shell --rit_name=Dennis --rit_coffee_type=espresso --rit_delivery=false

  node-action_job:
    runs-on: ubuntu-latest
    name: Ritchie Action Node
    needs: shell-action_job
    steps:
    - name: Run NODE Ritchie Action Command
      uses: GuillaumeFalourd/ritchie-action-node@v2.1
      with:
        rit-repo-url: https://github.com/ZupIT/ritchie-formulas-demo
        rit-formula-command: rit demo coffee-node --rit_name=Dennis --rit_coffee_type=espresso --rit_delivery=false

  python-action_job:
    runs-on: ubuntu-latest
    name: Ritchie Action Python
    needs: [shell-action_job, node-action_job]
    steps:
    - name: Run PYTHON Ritchie Action Command
      uses: GuillaumeFalourd/ritchie-action-python@v2.1
      with:
        rit-repo-url: https://github.com/ZupIT/ritchie-formulas-demo
        rit-formula-command: rit demo coffee-python --rit_name=Dennis --rit_coffee_type=espresso --rit_delivery=false

  java-action_job:
    runs-on: ubuntu-latest
    name: Ritchie Action Java
    needs: [python-action_job, node-action_job]
    steps:
    - name: Run JAVA Ritchie Action Command
      uses: GuillaumeFalourd/ritchie-action-java-8@v2.1
      with:
        rit-repo-url: https://github.com/ZupIT/ritchie-formulas-demo
        rit-formula-command: rit demo coffee-java --rit_name=Dennis --rit_coffee_type=espresso --rit_delivery=false

  go-action_job:
    runs-on: ubuntu-latest
    name: Ritchie Action Golang
    steps:
    - name: Run GOLANG Ritchie Action Command
      uses: GuillaumeFalourd/ritchie-action-go-15@v2.1
      with:
        rit-repo-url: https://github.com/ZupIT/ritchie-formulas-demo
        rit-formula-command: rit demo coffee-go --rit_name=Dennis --rit_coffee_type=espresso --rit_delivery=false
