name: 7 - Workflow Run Formula

on:
  workflow_run:
    workflows: ["1 - Formulas Scheduler (Default)"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "First workflow was a success"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "First workflow was a failure, trying again"
      - name: Ritchie Installation & Initialization
        run: |
          curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash
          echo '{"addCommons":false, "sendMetrics":true, "runType":"local"}' | rit init --stdin

      - name: Ritchie Formula Hello World (Golang) Execution
        run: |
          rit add repo --provider="Github" --name="demo" --repoUrl="https://github.com/ZupIT/ritchie-formulas-demo" --priority=1
          rit demo hello-world --rit_input_text="Dennis" --rit_input_boolean=true --rit_input_list="everything" --rit_input_password="Ritchie"