name: 8 - Formulas Scheduler Any OS (Action)

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:

  ubuntu-public:
    runs-on: ubuntu-latest
    steps:
      - uses: GuillaumeFalourd/ritchie-cli-action@main
        with:
          args: demo coffee-shell --rit_name=Dennis --rit_coffee_type=espresso --rit_delivery=false
          rit_repo_url: https://github.com/ZupIT/ritchie-formulas-demo
  
  ubuntu-private:
    runs-on: ubuntu-latest
    steps:
      - uses: GuillaumeFalourd/ritchie-cli-action@main
        with:
          args: python math sum numbers --number_one=1 --number_two=2
          rit_repo_url: https://github.com/GuillaumeFalourd/formulas-training
          access_token: ${{ secrets.ACCESS_TOKEN }}

  macos-public:
    runs-on: macos-latest
    steps:
      - uses: GuillaumeFalourd/ritchie-cli-action@main
        with:
          args: demo coffee-shell --rit_name=Dennis --rit_coffee_type=espresso --rit_delivery=false
          rit_repo_url: https://github.com/ZupIT/ritchie-formulas-demo
  
  macos-private:
    runs-on: macos-latest
    steps:
      - uses: GuillaumeFalourd/ritchie-cli-action@main
        with:
          args: python math sum numbers --number_one=1 --number_two=2
          rit_repo_url: https://github.com/GuillaumeFalourd/formulas-training
          access_token: ${{ secrets.ACCESS_TOKEN }}

  windows-public:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/ritchie-cli-action@main
        with:
          args: demo coffee-python --rit_name=Dennis --rit_coffee_type=espresso --rit_delivery=false
          rit_repo_url: https://github.com/ZupIT/ritchie-formulas-demo
  
  windows-private:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/ritchie-cli-action@main
        with:
          args: python math sum numbers --number_one=1 --number_two=2
          rit_repo_url: https://github.com/GuillaumeFalourd/formulas-training
          access_token: ${{ secrets.ACCESS_TOKEN }}