name: Formulas Scheduler Secrets

on:
  schedule:
  - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ritclizup/rit-python3-runner
      - id: execute-hello-world-formula
        name: Execute Ritchie Formula Hello World
        env:
            USERNAME_DEMO: ${{ secrets.USERNAME_DEMO }}
            USERNAME_CREDENTIAL: ${{ secrets.USERNAME_CREDENTIAL }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash
            echo '{"addCommons":false, "sendMetrics":true, "runType":"local"}' | rit init --stdin
            echo '{"provider":"Github", "name":"formulas-github", "url":"https://github.com/GuillaumeFalourd/formulas-github", "priority":1}' | rit add repo --stdin
            rit set credential --provider=github --fields=username,token --values="$USERNAME_CREDENTIAL","$GITHUB_TOKEN"
            rit github get user --github_username="$USERNAME_DEMO" --repo_details="no" --keep_file="no"
