name: Formulas Scheduler (with Dockerfile)

on:
  schedule:
  - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Installing Docker
          run: |
             sudo apt update
             sudo apt install apt-transport-https ca-certificates curl software-properties-common
             curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
             sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
             sudo apt update
             apt-cache policy docker-ce
             sudo apt install docker-ce
             sudo systemctl status docker

        - name: Ritchie Installation & Initialization
          run: |
             curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash
             echo '{"addCommons":false, "sendMetrics":true, "runType":"local"}' | rit init --stdin

        - name: Ritchie Formula Hello World (Golang) Execution using formula Dockerfile
          run: |
             sudo rit add repo --provider="Github" --name="demo" --repoUrl="https://github.com/ZupIT/ritchie-formulas-demo" --priority=1
             sudo rit demo hello-world --rit_input_text="Dennis" --rit_input_boolean=true --rit_input_list="everything" --rit_input_password="Ritchie" --docker
