name: Formulas Scheduler (with Secrets)

on:
  schedule:
  - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: docker://guillaumefalourd/ritchiecli:py-3.8
    steps:
      - name: Ritchie Formula Get Github User (Python) Execution
        env:
            USERNAME_DEMO: ${{ secrets.USERNAME_DEMO }}
            USERNAME_CREDENTIAL: ${{ secrets.USERNAME_CREDENTIAL }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            sudo rit add repo --provider="Github" --name="formulas-github" --repoUrl="https://github.com/GuillaumeFalourd/formulas-github" --priority=1
            sudo rit set credential --provider=github --fields=username,token --values="$USERNAME_CREDENTIAL","$GITHUB_TOKEN"
            sudo rit github get user --github_username="$USERNAME_DEMO" --repo_details="no" --keep_file="no"
